# Generated by Django 6.0.3 on 2026-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('UNDER_REVIEW', 'Under Review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20),
        ),
    ]
