# Generated by Django 6.0.2 on 2026-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('UNDER_REVIEW', 'Under Review'), ('REQ_CLARIFICATION', 'Request Clarification'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20),
        ),
    ]
