# Generated by Django 6.0.1 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE incidents_incident "
                        "ADD COLUMN IF NOT EXISTS is_anonymous boolean NOT NULL DEFAULT false;"
                    ),
                    reverse_sql="ALTER TABLE incidents_incident DROP COLUMN IF EXISTS is_anonymous;",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE incidents_incident "
                        "ADD COLUMN IF NOT EXISTS reporter_email varchar(254) NOT NULL DEFAULT '';"
                    ),
                    reverse_sql="ALTER TABLE incidents_incident DROP COLUMN IF EXISTS reporter_email;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE incidents_incident ALTER COLUMN reporter_email DROP DEFAULT;",
                    reverse_sql=(
                        "ALTER TABLE incidents_incident "
                        "ALTER COLUMN reporter_email SET DEFAULT '';"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="incident",
                    name="is_anonymous",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="incident",
                    name="reporter_email",
                    field=models.EmailField(blank=True, max_length=254),
                ),
            ],
        ),
    ]
