# Generated by Django 6.0.1 on 2026-03-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    # Compatibility placeholder for databases that already recorded this branch.
    # The actual idempotent schema/state update lives in 0003.
    operations = []
