# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


def ensure_incident_anonymous_fields(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    connection = schema_editor.connection
    table_name = Incident._meta.db_table
    quote = schema_editor.quote_name

    with connection.cursor() as cursor:
        existing_columns = {
            column.name for column in connection.introspection.get_table_description(cursor, table_name)
        }

    if "is_anonymous" not in existing_columns:
        field = models.BooleanField(default=False)
        field.set_attributes_from_name("is_anonymous")
        schema_editor.add_field(Incident, field)
    else:
        with connection.cursor() as cursor:
            cursor.execute(
                f"UPDATE {quote(table_name)} "
                f"SET {quote('is_anonymous')} = %s "
                f"WHERE {quote('is_anonymous')} IS NULL",
                [False],
            )

    if "reporter_email" not in existing_columns:
        field = models.EmailField(max_length=254, blank=True, default="")
        field.set_attributes_from_name("reporter_email")
        schema_editor.add_field(Incident, field)
    else:
        with connection.cursor() as cursor:
            cursor.execute(
                f"UPDATE {quote(table_name)} "
                f"SET {quote('reporter_email')} = %s "
                f"WHERE {quote('reporter_email')} IS NULL",
                [""],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_alter_incident_status_incidentcomment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_incident_anonymous_fields,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="incident",
                    name="is_anonymous",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="incident",
                    name="reporter_email",
                    field=models.EmailField(blank=True, default="", max_length=254),
                ),
            ],
        ),
    ]
