# Generated by Django 6.0.1 on 2026-03-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_anonymous_and_reporter_email'),
        ('incidents', '0003_incident_anonymous_and_reporter_email'),
    ]

    operations = [
    ]
