# Generated by Django 6.0.2 on 2026-03-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_incident_anonymous_and_reporter_email"),
        ("incidents", "0003_incident_anonymous_and_reporter_email"),
    ]

    operations = []
