# Generated by Django 6.0.2 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0005_incidentevidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="public_tracking_id",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="public_tracking_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
