# Generated by Django 6.0.1 on 2026-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_merge_20260313_1137'),
        ('incidents', '0006_incident_public_tracking_fields'),
    ]

    operations = [
    ]
